#!/bin/sh

case "$1" in
    start)
        echo "Loading aesdchar module"
        /usr/bin/aesdchar_load

        ;;
    stop)
        echo "Unloading aesdchar module"
        /usr/bin/aesdchar_unload

        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

